# Generated by Django 4.1.4 on 2023-01-05 14:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('json', models.JSONField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150, null=True)),
                ('names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), size=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('long', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
            ],
        ),
    ]
