# Generated by Django 4.1.4 on 2023-01-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoitem',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
