# Generated by Django 4.1.4 on 2023-01-16 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_service', '0002_photoitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoitem',
            name='names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), size=None),
        ),
    ]
