# Generated by Django 4.1.4 on 2023-01-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_service', '0003_alter_photoitem_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoitem',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
