# Generated by Django 4.1.4 on 2023-09-25 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=5)),
                ('valid_until_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('currency', models.CharField(blank=True, choices=[('EUR', 'Euro'), ('GBP', 'British Pound'), ('USD', 'US Dollar'), ('RUB', 'Russian Ruble')], default='RUB', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('discounts', models.ManyToManyField(related_name='orders', to='stripe_payments.discount')),
                ('items', models.ManyToManyField(to='stripe_payments.item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDiscountTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_payments.discount')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_payments.order')),
            ],
        ),
    ]
