# Generated by Django 4.1.4 on 2023-09-25 15:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngFixer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('input_sentence', models.CharField(max_length=256, unique=True)),
                ('translatedRU', models.CharField(max_length=256, null=True)),
                ('fixed_sentence', models.JSONField(null=True)),
                ('fixed_result', models.CharField(blank=True, max_length=256)),
                ('rephrases_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), null=True, size=None)),
                ('mistakes', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
