# Generated by Django 4.2.5 on 2023-10-11 10:09

import django.contrib.postgres.fields
from django.db import migrations, models
import eng_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngFixer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('input_sentence', models.CharField(max_length=256, unique=True, validators=[eng_service.models.validate_text_string])),
                ('translated_RU', models.CharField(max_length=256, null=True)),
                ('fixed_result_JSON', models.JSONField(null=True)),
                ('fixed_sentence', models.CharField(blank=True, max_length=256)),
                ('rephrases_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), null=True, size=None)),
                ('mistakes', models.CharField(max_length=256, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
