# Generated by Django 4.2.5 on 2023-10-11 07:47

from django.db import migrations, models
import eng_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('eng_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engfixer',
            name='input_sentence',
            field=models.CharField(max_length=256, unique=True, validators=[eng_service.models.validate_text_string]),
        ),
    ]
