# Generated by Django 4.2.5 on 2023-10-11 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eng_service', '0002_alter_engfixer_input_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='engfixer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
