# Generated by Django 4.2.5 on 2023-10-26 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eng_service', '0003_userprofile_alter_request_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user',
            new_name='user_profile',
        ),
    ]
