# Generated by Django 4.2.5 on 2023-11-02 14:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng_service', '0005_remove_engfixer_translated_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engfixer',
            old_name='mistakes',
            new_name='mistakes_most_TMP',
        ),
        migrations.AddField(
            model_name='engfixer',
            name='mistakes_list_TMP',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), null=True, size=None),
        ),
    ]
