# Generated by Django 4.2.5 on 2023-11-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng_service', '0006_rename_mistakes_engfixer_mistakes_most_tmp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('str_name', models.CharField(max_length=256, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='tagname_idx')],
            },
        ),
    ]
