# Generated by Django 4.2.5 on 2023-11-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng_service', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='engfixer',
            name='tags',
            field=models.ManyToManyField(null=True, to='eng_service.tag'),
        ),
    ]
