# Generated by Django 4.2.5 on 2024-02-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng_service', '0010_engfixer_its_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engfixer',
            name='tags',
            field=models.ManyToManyField(to='eng_service.tag'),
        ),
        migrations.AddConstraint(
            model_name='engfixer',
            constraint=models.UniqueConstraint(fields=('id', 'input_sentence'), name='unique_id_input_sentence'),
        ),
    ]
