# Generated by Django 4.2.5 on 2024-03-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng_service', '0011_alter_engfixer_tags_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='engfixer',
            index=models.Index(fields=['its_correct'], name='its_correct_idx'),
        ),
    ]
