# Generated by Django 4.2.5 on 2025-01-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng_service', '0012_engfixer_its_correct_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='engfixer',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
