# Generated by Django 4.2.18 on 2025-02-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eng_service', '0013_engfixer_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engfixer',
            name='mistakes_list_TMP',
        ),
        migrations.RemoveField(
            model_name='engfixer',
            name='mistakes_most_TMP',
        ),
    ]
