# Generated by Django 4.1.4 on 2023-02-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0005_alter_discount_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='stripe_service.item')),
            ],
        ),
        migrations.CreateModel(
            name='Discount2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=5)),
                ('valid_until_date', models.DateTimeField()),
                ('orders', models.ManyToManyField(related_name='discount_set2', to='stripe_service.order')),
            ],
        ),
    ]
