# Generated by Django 4.1.4 on 2023-02-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0006_order2_discount2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount2',
            name='orders',
            field=models.ManyToManyField(related_name='discount_set2', to='stripe_service.order2'),
        ),
    ]
