# Generated by Django 4.1.4 on 2023-03-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0007_alter_discount2_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount2',
            name='orders',
            field=models.ManyToManyField(related_name='discount2_set', to='stripe_service.order2'),
        ),
    ]
