# Generated by Django 4.1.4 on 2023-03-19 16:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0010_remove_discount_orders_order_discounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngFixer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('input_sentence', models.CharField(max_length=256)),
                ('translatedRU', models.CharField(max_length=256, null=True)),
                ('fixed_result', models.CharField(max_length=256)),
                ('rephrases_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), null=True, size=None)),
                ('mistakes', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDiscountTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_service.discount')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_service.order')),
            ],
        ),
    ]
