# Generated by Django 4.1.4 on 2023-03-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0014_engfixer_correct_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engfixer',
            name='fixed_result_JSON',
            field=models.JSONField(null=True),
        ),
    ]
