# Generated by Django 4.1.4 on 2023-02-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
