# Generated by Django 4.1.4 on 2023-02-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0002_alter_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='id',
        ),
    ]
