# Generated by Django 4.1.4 on 2023-02-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0003_rename_item_id_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Euro'), ('GBP', 'British Pound'), ('USD', 'US Dollar'), ('RUB', 'Russian Ruble')], default='RUB', max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('items', models.ManyToManyField(to='stripe_service.item')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=5)),
                ('valid_until_date', models.DateTimeField()),
                ('orders', models.ManyToManyField(to='stripe_service.order')),
            ],
        ),
    ]
