# Generated by Django 4.1.4 on 2023-02-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0004_item_currency_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='orders',
            field=models.ManyToManyField(related_name='discount_set', to='stripe_service.order'),
        ),
    ]
