# Generated by Django 4.1.4 on 2023-03-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0008_alter_discount2_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order2',
            name='items',
        ),
        migrations.DeleteModel(
            name='Discount2',
        ),
        migrations.DeleteModel(
            name='Order2',
        ),
    ]
