# Generated by Django 4.1.4 on 2023-03-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0009_remove_order2_items_delete_discount2_delete_order2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(related_name='orders', to='stripe_service.discount'),
        ),
    ]
