# Generated by Django 4.1.4 on 2023-03-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0012_alter_engfixer_fixed_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engfixer',
            name='input_sentence',
            field=models.CharField(max_length=256),
        ),
    ]
