# Generated by Django 4.1.4 on 2023-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_service', '0015_alter_engfixer_correct_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engfixer',
            name='input_sentence',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AddConstraint(
            model_name='engfixer',
            constraint=models.UniqueConstraint(fields=('id', 'input_sentence'), name='unique_id_input_sentence'),
        ),
    ]
